services:
  - type: web
    name: laravel-prestamos
    env: php
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: prestamos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: prestamos-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: prestamos-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: prestamos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: prestamos-db
          property: password

databases:
  - name: prestamos-db
    databaseName: prestamos
    user: prestamos_user
    plan: free
    region: oregon
